sudo: required
services:
  - docker

before_install:
  - docker build -t michalszczep/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true michalszczep/docker-react npm run test -- --coverage